apiVersion: v1
kind: ConfigMap
metadata:
  name: kyueksel-index-html-configmap
  namespace: nginx
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! I got deployed in dev-kyueksel Environment using Helm Chart </h1>
    </html
