apiVersion: v1
kind: Service
metadata:
  name: kyueksel-service
  namespace: nginx
spec:
  selector:
    app.kubernetes.io/instance: kyueksel
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 9000
