apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
  namespace: nginx
  annotations:
    clusterconfig.azure.com/use-managed-source: "true"
spec:
  interval: 1m
  releaseName: nginx
  chart:
    spec:
      chart: ./nginx/chart
  values:
    controller:
      image:
        repository: nginx
        tag: "latest"
      replicaCount: 3